/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.mant.vista.image.pantalla;

import Com.mant.controladorVO.UsuariosVO;

/**
 *
 * @author User
 */
public class Principal2 extends javax.swing.JFrame {

    UsuariosVO mod;

    public Principal2() {
        initComponents();

    }

    public Principal2(UsuariosVO mod) {

        initComponents();
        this.setLocationRelativeTo(this);
        this.btHmoe.setSelected(true);
        //setLocationRelativeTo(null);        
        jtUsertf.setText(mod.getUsuario());
        this.mod = mod;
        if (mod.getId_tipo() == 1 || mod.getId_tipo() == 3) {
            btCalculoMant.setVisible(true);
            btnUser.setVisible(true);
            btnRegMotos.setVisible(true);
            btnRegCarroceria.setVisible(true);
            btnabrArchiv.setVisible(true);
            btnRegAutos.setVisible(true);
        } else if (mod.getId_tipo() == 2 || mod.getId_tipo() == 4) {
            btCalculoMant.setVisible(false);
            btnUser.setVisible(false);
            btnRegMotos.setVisible(false);
            btnRegCarroceria.setVisible(false);
            btnabrArchiv.setVisible(false);
            btnRegAutos.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnMenu = new javax.swing.JButton();
        jtUsertf = new javax.swing.JLabel();
        pnMenu = new javax.swing.JPanel();
        btHmoe = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btRegistroGeneral = new javax.swing.JButton();
        btCalculoMant = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btCambiPass = new javax.swing.JButton();
        btCalculoMant_asesor = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnRegMotos = new javax.swing.JButton();
        btnRegCarroceria = new javax.swing.JButton();
        btnRegMotor = new javax.swing.JButton();
        btnabrArchiv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegAutos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setText("ECUAVIA S.A.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("USUARIO:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 40, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 60, 160, 10));

        btnMenu.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/man/vista/image/icons8_Menu_32px_1.png"))); // NOI18N
        btnMenu.setText("MENU");
        btnMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel2.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 40));

        jtUsertf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel2.add(jtUsertf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 40, 140, 20));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 110));

        pnMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btHmoe.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btHmoe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/man/vista/image/iconfinder_home_353416.png"))); // NOI18N
        btHmoe.setText("            Home");
        btHmoe.setBorder(null);
        btHmoe.setBorderPainted(false);
        btHmoe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHmoe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btHmoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHmoeActionPerformed(evt);
            }
        });
        pnMenu.add(btHmoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 330, 57));

        jButton4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton4.setText("Cerrar sesion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnMenu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 581, -1, -1));

        btRegistroGeneral.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btRegistroGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/man/vista/image/iconfinder_application_form_magnify_35651.png"))); // NOI18N
        btRegistroGeneral.setText("          Editar registro");
        btRegistroGeneral.setBorder(null);
        btRegistroGeneral.setBorderPainted(false);
        btRegistroGeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRegistroGeneral.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btRegistroGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistroGeneralActionPerformed(evt);
            }
        });
        pnMenu.add(btRegistroGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 330, 60));

        btCalculoMant.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btCalculoMant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/man/vista/image/web.png"))); // NOI18N
        btCalculoMant.setText("         Calcular mantenimiento ");
        btCalculoMant.setBorder(null);
        btCalculoMant.setBorderPainted(false);
        btCalculoMant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCalculoMant.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCalculoMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalculoMantActionPerformed(evt);
            }
        });
        pnMenu.add(btCalculoMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 330, 60));

        btnUser.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/man/vista/image/icons8_customer_32px_1.png"))); // NOI18N
        btnUser.setText("          Agregar usuario");
        btnUser.setBorder(null);
        btnUser.setBorderPainted(false);
        btnUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        pnMenu.add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 330, 60));

        btCambiPass.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btCambiPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/man/vista/image/iconfinder_password_2639882.png"))); // NOI18N
        btCambiPass.setText("         Cambiar contraseña");
        btCambiPass.setBorder(null);
        btCambiPass.setBorderPainted(false);
        btCambiPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCambiPass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCambiPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCambiPassActionPerformed(evt);
            }
        });
        pnMenu.add(btCambiPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 330, 60));

        btCalculoMant_asesor.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btCalculoMant_asesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/man/vista/image/web.png"))); // NOI18N
        btCalculoMant_asesor.setText("          Calcular mantenimiento Asesor");
        btCalculoMant_asesor.setBorder(null);
        btCalculoMant_asesor.setBorderPainted(false);
        btCalculoMant_asesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCalculoMant_asesor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCalculoMant_asesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalculoMant_asesorActionPerformed(evt);
            }
        });
        pnMenu.add(btCalculoMant_asesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 330, 60));

        jPanel3.add(pnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 330, 630));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setText("Registro general vehiculo");

        btnRegMotos.setText("Registro motos");
        btnRegMotos.setEnabled(false);
        btnRegMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegMotosActionPerformed(evt);
            }
        });

        btnRegCarroceria.setText("Registro por carroceria");
        btnRegCarroceria.setEnabled(false);

        btnRegMotor.setText("Registro por motor");
        btnRegMotor.setEnabled(false);

        btnabrArchiv.setText("Abrir archivos");
        btnabrArchiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabrArchivActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/man/vista/image/43b40b0dfcbaafcc9d0d516b26f34a84.gif"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/man/vista/image/505.gif"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/man/vista/image/car_xodoafpu.gif"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/man/vista/image/02d44a138596fdf4ae697bf05eaa6285.gif"))); // NOI18N

        btnRegAutos.setText("Registro autos");
        btnRegAutos.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(358, 358, 358)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel5)
                                    .addGap(48, 48, 48)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnRegMotos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnRegCarroceria, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnabrArchiv, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnRegMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRegAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(btnRegMotos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRegCarroceria, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnabrArchiv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnRegMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnRegAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 1050, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Login log = new Login();
        this.dispose();
        log.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void btRegistroGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistroGeneralActionPerformed
        Home hm = new Home();
        hm.setVisible(true);

    }//GEN-LAST:event_btRegistroGeneralActionPerformed

    private void btHmoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHmoeActionPerformed

    }//GEN-LAST:event_btHmoeActionPerformed

    private void btCalculoMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalculoMantActionPerformed
        Mantenimiento mant = new Mantenimiento();
        mant.setVisible(true);

    }//GEN-LAST:event_btCalculoMantActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        registroUsuariosEC user = new registroUsuariosEC();
        user.setVisible(true);
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        int posicion = this.pnMenu.getX();
        if (posicion > -1) {
            Animacion.Animacion.mover_izquierda(0, -330, 2, 2, pnMenu);
        } else {
            Animacion.Animacion.mover_derecha(-330, 0, 2, 2, pnMenu);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btCambiPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCambiPassActionPerformed
        cambioContraseña chpass = new cambioContraseña();
        chpass.setVisible(true);
    }//GEN-LAST:event_btCambiPassActionPerformed

    private void btnRegMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegMotosActionPerformed

    }//GEN-LAST:event_btnRegMotosActionPerformed

    private void btnabrArchivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabrArchivActionPerformed
        abrirArchivos ab = new abrirArchivos();
        ab.setVisible(true);
    }//GEN-LAST:event_btnabrArchivActionPerformed

    private void btCalculoMant_asesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalculoMant_asesorActionPerformed
        Mantenimiento_asesor mant = new Mantenimiento_asesor();
        mant.setVisible(true);
    }//GEN-LAST:event_btCalculoMant_asesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalculoMant;
    private javax.swing.JButton btCalculoMant_asesor;
    private javax.swing.JButton btCambiPass;
    private javax.swing.JButton btHmoe;
    private javax.swing.JButton btRegistroGeneral;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegAutos;
    private javax.swing.JButton btnRegCarroceria;
    private javax.swing.JButton btnRegMotor;
    private javax.swing.JButton btnRegMotos;
    private javax.swing.JButton btnUser;
    public javax.swing.JButton btnabrArchiv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jtUsertf;
    private javax.swing.JPanel pnMenu;
    // End of variables declaration//GEN-END:variables
}
